name: signing_files
on:
   push:
    branches: [ main ]
permissions:
    id-token: write

jobs:
  signing_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: python -m pip install .
      - uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: README.md