name: sign-readme
on:
    push:
        branches: [ main ]
jobs:
  sign-readme:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
        - uses: actions/checkout@v3
        - uses: sigstore/gh-action-sigstore-python@v3.0.0
          with:
            inputs: README.md to_be_signed.txt