name: sign-readme
on:
    push:
        branches: [ main ]
jobs:
  sign-readme:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
        - uses: actions/checkout@v3
        - uses: sigstore/gh-action-sigstore-python@v3.0.0
          with:
            inputs: README.md
            verify: true
            verify-cert-identity: https://github.com/hayleycd/testing-python-github-action/.github/workflows/signing.yaml@refs/heads/main
            verify-oidc-issuer: https://token.actions.githubusercontent.com
