on:
    push:
        branches: [ main ]
jobs:
  selftest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: 
        sigstore/gh-action-sigstore-python@v3.0.0
    - run: python -m pip install .