name: sign-readme
on:
    push:
        branches: [ main ]
jobs:
  sign-readme:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
        - uses: sigstore/gh-action-sigstore-python@v3.0.0
          with:
            inputs: "./to_be_signed.txt"
            internal-be-careful-debug: true